BEGIN;
CREATE DATABASE IF NOT EXISTS Fact;
USE Fact;

CREATE TABLE STORE (
	STR_ID 		NUMERIC(10,0) PRIMARY KEY
);

CREATE TABLE PRODUCT (
	STR_ID		NUMERIC(10,0),
    FOREIGN KEY(STR_ID) REFERENCES STORE(STR_ID),
    ITM_NUM 	NUMERIC(10,0) PRIMARY KEY,
    ITM_DATE	DATE,
    ITM_NAME	VARCHAR(45),
	ITM_COST	NUMERIC(10,0),
    ITM_AMT	NUMERIC(65,0)
);

CREATE TABLE REMOVED_ITEMS (
ITM_NUM NUMERIC(10,0),
FOREIGN KEYS(ITM_NUM) REFERENCES PRODUCT(ITM_NUM)
ITM_NAME VARCHAR(45),
ITM_REASON VARCHAR(45)
);





